title: Breanna E. Green
logo: /assets/img/headshot_lrg.jpeg
description: A website to view B. E. Green recent works and projects.
show_downloads: true
icon: /assets/img/cartoon_avi.jpg
google_analytics:
theme: jekyll-theme-minimal
